group 'org.forgerock.forgerock_authenticator'
version '1.0-SNAPSHOT'

buildscript {
    ext.kotlin_version = '2.1.0'
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.9.1'
        classpath 'com.google.gms:google-services:4.4.2'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

android {
    namespace 'org.forgerock.forgerock_authenticator'
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    defaultConfig {
        minSdkVersion 23
        consumerProguardFiles 'proguard-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.annotation:annotation:1.6.0'
    implementation 'androidx.activity:activity-ktx:1.7.2'
    implementation 'com.google.firebase:firebase-messaging:23.1.2'
    implementation 'com.google.android.gms:play-services-location:21.0.1'

    implementation 'org.forgerock:forgerock-authenticator:4.8.3'
    implementation 'org.forgerock:forgerock-core:4.8.3'

    //add lib via aar-depency
//    implementation(name: 'forgerock-authenticator-debug', ext: 'aar')
//    implementation(name: 'forgerock-core-debug', ext: 'aar')
//    implementation 'com.nimbusds:nimbus-jose-jwt:9.0.1'
//    implementation 'com.squareup.okhttp3:okhttp:4.3.1'
//    implementation 'com.squareup.okhttp3:logging-interceptor:4.3.1'
//    implementation 'androidx.biometric:biometric-ktx:1.2.0-alpha05'

}