name: forgerock_authenticator_example
description: Demonstrates how to use the forgerock_authenticator plugin.
version: 3.0.0+1

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  forgerock_authenticator:
    # When depending on this package from a real application you should use:
    #   forgerock_authenticator: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

  cupertino_icons:
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  shared_preferences: ^2.0.8
  local_auth: ^1.1.8
  sqflite: ^2.0.1
  uuid: ^3.0.5
  path: ^1.8.0
  base32: ^2.1.1
  url_launcher: ^6.0.17
  logging: ^1.0.2
  package_info_plus: ^1.3.0
  qr_code_scanner: ^0.6.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.0.10
  golden_toolkit: ^0.9.0

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/images/fr-logo-white.png
    - assets/images/fr-logo-black.png
    - assets/images/fr-logo-color.png
    - assets/images/fr-icon-lock.png
    - assets/images/fr-icon-mfa.png
    - assets/images/fr-icon-add-accounts.png
    - assets/images/fr-icon-no-accounts.png
    - assets/images/fr-icon-accounts-lock.png
    - assets/images/fr-icon-biometric.png
    - assets/images/fr-icon-cloud.png
    - assets/images/fr-icon-no-notifications.png
    - assets/images/fr-icon-watch.png
    - assets/images/fr-icon-welcome.png
    - assets/images/fr-icon-sync.png
    - assets/images/fr-logo-white-no-text.png
    - assets/images/fr-logo-color-no-text.png
    - assets/images/fr-background-logo.png
    - assets/images/fr-icon-delete-account.png

  # Enable generation of localized Strings from arb files.
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
