name: New Issue Report

on:
  issues:
    types: [opened]

jobs:
  new-issue-handler:
    runs-on: ubuntu-latest
    steps:
      # Add a comment to the issue, informing the reporter that we'll get back to them soon
      - name: Add a comment to newly created issue.
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!\nThe team will be notified and will get back to you soon!'
            })
    
      # Label the ticket as "new"
      - name: Add a label to the newly created issue.
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['new']
            })

      # Send a slack notification to inform the team about the new ticket
      - name: Send a slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: all
          custom_payload: |
            {
              attachments: [{
                title: '‼️ New issue created in <${{ github.event.repository.html_url }}|${{ github.event.repository.name }} > repo by user <${{ github.event.issue.user.html_url }}|${{ github.event.issue.user.login }}>',
                color: 'danger',
                text: `\n*Title:* ${{ github.event.issue.title}}\n*URL:* ${{ github.event.issue.html_url }}`, 
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}